;===============EXTENSION 1000
[1000](endpoint-basic)
type=endpoint
callerid=<1000>
auth=auth1000
aors=1000
mailboxes=1000@default
voicemail_extension=1000
transport=udp-transport

[auth1000](auth-userpass)
password=ePCLk3reao8O
username=tyBpkQY5

[1000](aor-single-reg)
voicemail_extension=1000


;===============EXTENSION 1001
[1001](endpoint-basic)
type=endpoint
callerid=<1001>
auth=auth1001
aors=1001
mailboxes=1001@default
voicemail_extension=1001
transport=tls-transport
media_encryption=sdes
media_encryption_optimistic=yes

[auth1001](auth-userpass)
password=Sw6Nmb4iDfAD
username=JCg4n4ns

[1001](aor-single-reg)
voicemail_extension=1001


;===============EXTENSION 1002
[1002](endpoint-basic)
type=endpoint
callerid=<1002>
auth=auth1002
aors=1002
mailboxes=1002@default
voicemail_extension=1002
transport=udp-transport

[auth1002](auth-userpass)
password=RCFUflPY6abH
username=rWtZcQWw

[1002](aor-single-reg)
voicemail_extension=1002


;===============EXTENSION 1003
[1003](endpoint-basic)
type=endpoint
callerid=<1003>
auth=auth1003
aors=1003
mailboxes=1003@default
voicemail_extension=1003
transport=tls-transport
media_encryption=sdes
media_encryption_optimistic=yes

[auth1003](auth-userpass)
password=Y0DV5MrAqQy8
username=mztKSsIZ

[1003](aor-single-reg)
voicemail_extension=1003


;===============EXTENSION 1004
[1004](endpoint-basic)
type=endpoint
callerid=<1004>
auth=auth1004
aors=1004
mailboxes=1004@default
voicemail_extension=1004
transport=udp-transport

[auth1004](auth-userpass)
password=RURD84KQ9JZ1
username=jaKZT7Cn

[1004](aor-single-reg)
voicemail_extension=1004


;===============EXTENSION 1005
[1005](endpoint-basic)
type=endpoint
callerid=<1005>
auth=auth1005
aors=1005
mailboxes=1005@default
voicemail_extension=1005
transport=tls-transport
media_encryption=sdes
media_encryption_optimistic=yes

[auth1005](auth-userpass)
password=ko76BaaDHUMA
username=sSvsdJYP

[1005](aor-single-reg)
voicemail_extension=1005


;===============EXTENSION 1006
[1006](endpoint-basic)
type=endpoint
callerid=<1006>
auth=auth1006
aors=1006
mailboxes=1006@default
voicemail_extension=1006
transport=tls-transport
media_encryption=sdes
media_encryption_optimistic=yes

[auth1006](auth-userpass)
password=ko76BaaDHUMA
username=sSvsdJYP

[1006](aor-single-reg)
voicemail_extension=1006


